apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      env: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        env: dev
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageurl }}:{{ .Values.deployment.imageversion }}"
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: catalogue
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
    

